### ISSUE TITLE
Status bar hide/show

### ISSUE THREAD

**Issue by Angelk90** [sanpyaelin/react-native-collapsingtoolbar#3]
@sanpyaelin:

It would be possible to make sure that when you see the complete image, the status bar is hidden, so you can see the whole image.
Instead when you can not see the image, ie you see the toolbar, the status bar returns to appear.

<StatusBar hidden = {false} />
<StatusBar hidden = {true} />

**Comment by sanpyaelin** [comment]
Yeah. It is possible. I will add this feature on next version.
